### ISSUE TITLE
Gem of Eternal Density and Dark Matter Furnace research overlaps

### ISSUE THREAD

**Issue by bloxgate** [Lilylicious/ThaumicEquivalence#14]
Hi, the research for the Gem of Eternal Density isn't being loaded since it overlaps with that of the Dark Matter furnace.

**Comment by O13SC3N3** [comment]
@Lilylicious 

Found It,

**LINE 43** new ResearchItem("DMFURNACE", "TE_CATEGORY", AspectLists.dmFurnaceResearch, **2, -5, 1,** new ItemStack(ObjHandler.dmFurnaceOn)).setPages(new ResearchPage("te.research_page.DMFURNACE.1"), new ResearchPage(ThaumicRecipes.dmFurnace)).setParents(new String[]{"DARKMATTER"}).setConcealed().registerResearchItem();
**LINE 46** new ResearchItem("DENSITYGEM", "TE_CATEGORY", AspectLists.densityGemResearch, **2, -5, 1**, new ItemStack(ObjHandler.eternalDensity)).setPages(new ResearchPage("te.research_page.DENSITYGEM.1"), new ResearchPage(ThaumicRecipes.densityGem)).setParents(new String[]{"DARKMATTER"}).setConcealed().registerResearchItem();
