### ISSUE TITLE
Research for Hardmode.

### ISSUE THREAD

**Issue by lilmoefow** [Lilylicious/ThaumicEquivalence#16]
Did i mess something up in the configs?  Cause all the research i have done so far looks like this 

http://imgur.com/kLcpDQQ

Here is what the configs looks like

http://pastebin.com/ACTe0XDD

Is this mod still being worked on? Should i give up trying to find a fix for this?

EDIT:

I'm just be a derp. and only some of the beginning research is really easy like the picture posted.  its now adding in one more aspect to connect atleast.

**Comment by psychofad** [comment]
I was wondering myself since using Thaumcraft Research Helper with those 1 aspect researches will crash you to desktop, on a hunch I placed the research into the table and found the easiest research to date staring me in the face.  Good to know I am not the only one seeing this, but I feel there should always be at least 2 aspects to every research just for sanity's sake at least.

**Comment by lilmoefow** [comment]
Seeing as the research is super easy, i have tweaked some of the recipes using minetweaker/modtweaker.  Keep in mind i disable all of the emc generation from vis values, which causes every item with in ProjectE to loose its EMC valuse (i do this on purpose, its a balance thing in my personal modpack)  If you are interested in seeing those changes, let me know.

**Comment by spannerman79** [comment]
> If you are interested in seeing those changes, let me know.

@lilmoefow yes please. I don't use ProjectE as i feel as ProjectE is too "cheaty" in my personal view. Pop those changes up into a gist as (i assume) it would be easier

**Comment by lilmoefow** [comment]
keep in mind this script requires thaumcraft, projectE, and thaumic equivalence.  I would also recomend using the same config settings i provided in the first post.

http://pastebin.com/TDfqLKPD

**Comment by Lilylicious** [comment]
Closing issue due to narrowing of scope in newer versions.
