### ISSUE TITLE
Mod needs a separate file for the tab icon

### ISSUE THREAD

**Issue by Shahelion** [Lilylicious/ThaumicEquivalence#17]
Since it uses the same file that Project E uses itself for the Philostone, if you have the old textures from the pack enabled, it tried to use the animated version, which...does not work. Having its own file, that can be replaced manually if needed, would be the optimal solution, I believe.

https://gyazo.com/333245b898805b88198754e27e6ebf93

**Comment by spannerman79** [comment]
On one hand - good idea.

Other hand - bad idea - players/packs will start to need https://minecraft.curseforge.com/projects/notenoughthaumcrafttabs/files/2266711

**Comment by Shahelion** [comment]
Um...what? Why would this particular thing cause players to need that mod? I only have it because I have a lot of add-ons.

**Comment by spannerman79** [comment]
Why?  Too many Thaumcraft tabs - painfully obvious.

**Comment by Shahelion** [comment]
What are you talking about? This is not an issue about having too many tabs, this is about the tab icon for THIS mod not working with a resource pack, because it can't support animations.

I KNOW I have too many tabs, that's why I already have that mod. But that is completely irrelevant to this issue.

**Comment by Lilylicious** [comment]
Closing issue due to narrowing of scope in newer versions.

**Comment by Shahelion** [comment]
I'm curious why this is being closed. Is the mod no longer going to be a Thaumcraft/Project E crossover mod? If it is, then this issue is definitely still valid unless there won't be any book entries anymore.

**Comment by Lilylicious** [comment]
As of right now, newer versions will not include hard mode, research and such. Previous versions will not be worked on. This may be revisited in the future, depending on how much time I have to work on it. I'd like to give it a better showing this time around with balance, if I do end up going that route.

**Comment by Shahelion** [comment]
I forgot that the modes were even a thing lol. I always used the research option. c:

**Comment by Lilylicious** [comment]
The fact that several people have asked for it to be ported to 1.12 has been a bit of an eye opener. Never thought the mod was very popular, but apparently I have fans. It does give more incentive to update it more fully.
