### ISSUE TITLE
Update to 1.10.2

### ISSUE THREAD

**Issue by Blu3wolf** [Lilylicious/ThaumicEquivalence#20]
I am completely unfamiliar with minecraft modding, so I ask with total ignorance: is this getting updated to newer versions? Is that a ridiculously hard request, or just further along on the to-do list?

**Comment by spannerman79** [comment]
https://github.com/Lilylicious/ThaumicEquivalence/issues/18#issuecomment-265200853

**Comment by Lilylicious** [comment]
The plan is definitely to update this to 1.10.2. The problem is, Thaumcraft isn't updated past 1.8.9 (as of yet), so I can't really update this until that happens.
