### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by renadi** [Lilylicious/ThaumicEquivalence#21]
I tried adding this to my pack and after a bunch of troubleshooting figured out Thaumic Equivalence was causing it to crash. 

Minecraft 1.12.2
Forge 14.23.3.2697

https://pastebin.com/NkwXjUgH

**Comment by Lilylicious** [comment]
Issue identified, fix in progress.

**Comment by Lilylicious** [comment]
Fix is being uploaded in version 1.0.1, should be available within about an hour.
