### ISSUE TITLE
NoSuchMethod crash with the latest beta version of ProjectE (PE1.3.1B)

### ISSUE THREAD

**Issue by malSet** [Lilylicious/ThaumicEquivalence#22]
Thaumic Equivalence crashes on startup with a NoSuchMethod exception with version PE1.3.1B of ProjectE. This might have to do with the fact that ProjectE switched from storing EMC as Ints and is instead storing them as Longs (sinkillerj/ProjectE#1709), but could also likely be any internal change on ProjectE's part.

Crash log available [here](https://pastebin.com/hcgjhsfz).

**Comment by Lilylicious** [comment]
I'm aware. Fix will come as soon as I've got my dev environment sorted again. Neglected to renew my license for my favourite environment, soooo it'll be a few days to a week somewhere.

**Comment by Lilylicious** [comment]
Fixed in version 1.0.3 which should be available within an hour or two.

**Comment by Lilylicious** [comment]
Correction, fixed in 1.0.4!
