### ISSUE TITLE
ThaumicEquivalence-1.12.2-1.0.3.jar Throws Exception upon Startup

### ISSUE THREAD

**Issue by WhisperFire26** [Lilylicious/ThaumicEquivalence#24]
Unable to load the modpack with ThaumicEquivalence-1.12.2-1.0.3.jar. Had to rollback with 1.0.2. Please investigate.

**Comment by WhisperFire26** [comment]
Other Mods running in this mod pack is:
ProjectE-1.12-PE1.3.1B.jar
Thaumcraft-1.12.2-6.1.BETA17.jar
ThaumicAdditions-1.12.2-3r.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThaumicJEI-1.12.2-1.4.0-14.jar

Maybe ThaumicEquivalence-1.12.2-1.0.3.jar is conflicting with one of these mods?

The modpack in question is called Magic Labs at: https://minecraft.curseforge.com/projects/magic-labs

**Comment by Lilylicious** [comment]
Got a crash log?

**Comment by WhisperFire26** [comment]
UPDATE: Found a solution - Rollback ProjectE from PE1.3.1B to PE1.3.0 and the latest version of ThaumicEquivalence will run. Please look into the ProjectE beta build for future development and close ticket.

Thank you.

**Comment by WhisperFire26** [comment]
Here is a copy of the crash report for future reference:

[crash-2018-07-03_15.56.48-client.txt](https://github.com/Lilylicious/ThaumicEquivalence/files/2160901/crash-2018-07-03_15.56.48-client.txt)

**Comment by Lilylicious** [comment]
So the fix is technically in 1.0.3, but I stupidly compiled it against 1.3.0 of ProjectE which meant it broke. After compiling against the right target, it works. 1.0.4!
