### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RoloEdits** [Lilylicious/ThaumicEquivalence#5]
http://pastebin.com/vBzKBYGV

**Comment by Lilylicious** [comment]
Do you happen to have any other thaumcraft add ons installed?

**Comment by RoloEdits** [comment]
Yes, Tinkerer, Exploration, Energistics, Witching Gadgets, NEI Plugin, Thaumcraft Minus Thaumcraft, Technomancy, Node Tracker, Tainted Magic, Nodal Mechanics, Magic Bees, Forbidden Magic an done or two other mods that add like one or two things as integration like railcraft.

**Comment by Lilylicious** [comment]
One or several of those are adding aspects and being loaded after this one. I'll have a fix later today.

**Comment by RoloEdits** [comment]
OK, thanks for the quick response :)

**Comment by Lilylicious** [comment]
Fixed as of version 1.0.1
