### ISSUE TITLE
Cannot Load World

### ISSUE THREAD

**Issue by spocane** [Lilylicious/ThaumicEquivalence#7]
Hi, using the latest versions of Thaumic Equivalence 1.0.1, and ProjectE 1.9.3 I am getting a crash when loading a world, while Generating EMC Values. It just boots you back to the main menu, the game does not crash.

It only happens when adding Thaumic Equivalence, fine with just ProjectE.

Taken from the Log:
http://pastebin.com/u0Psvxg6

**Comment by Lilylicious** [comment]
Quick fix would be to regenerate The pregenerate emc file. Figuring this one out requires expertise from a sleeping @MaPePeR

Note that this file may contain custom emc values that would be lost when deleting it.

**Comment by spocane** [comment]
That is when the crash is happening, when i delete the old pregenerated JSON file, start mc and have a new one generated, it just stops, and the JSON file is empty

**Comment by Lilylicious** [comment]
Very strange. I'm sure @MaPePeR will know what's up, he wrote all the json stuff.

**Comment by MaPePeR** [comment]
First fix would be to disable pregenerated emc, i guess...

**Comment by Lilylicious** [comment]
It's very strange. It seems to be complaining about an item ID, but if removing this mod fixes the problem it makes even less sense than a kitten on mars. This mod doesn't add items, not yet.

**Comment by Lilylicious** [comment]
I can't reproduce it either. What mods are you using beyond the three obvious ones(this, thaumcraft, ProjectE)?

**Comment by spocane** [comment]
Looking through NEI it appears that i do not have any item registered with the ID of 7770:0.

I do have many mods in my instance,

**Comment by Lilylicious** [comment]
There's a tentative fix being worked on that may or may not solve the problem. Since we can't reproduce the problem we can't test it either. We may link to a file with the fix in so you can see if it helps or not.

**Comment by spocane** [comment]
Ok,  tomorrow I will try to work through different mods i have and see if I can possibly find a culprit.

Thanks for looking into the issue.

**Comment by MaPePeR** [comment]
@spocane Could you try [this](https://github.com/MaPePeR/ProjectE/releases/tag/v1.9.3h-uniqueItemNamesInsteadIds) version of ProjectE, and see if it fixes the problem?

**Comment by spocane** [comment]
@MaPePeR That version works perfectly as far as i can tell. had no problems generating the pregenerated_emc.json file, and all the thaumcraft items now have their EMC.

Is that version of ProjectE suitable to use in my world or should i wait till an official release?

Thank you @MaPePeR and @Lilylicious for looking into/fixing the issue, i appreciate it!

**Comment by Lilylicious** [comment]
You can use it, though keep an eye out if anything weird happens. It shouldn't, but we want to test it more before it makes it into an official release. Don't distribute the prerelease or put it in a mod pack download or anything, but it's fine for personal use.

**Comment by spocane** [comment]
Ok,  will use it and test it!  I will let you know if any issues come up

**Comment by MaPePeR** [comment]
Thanks for testing!

Because it will probably take some time, before we have a new fixed ProjectE release: 
@Lilylicious
Replace the calls to the `registerEmc` method, where you use `Block` or `Item` with `ItemStack`. (so just wrap them) That should also fix the problem. 

The code that auto wraps these did go through the code path for objects/fluids and ore dictionary, which did not do safeguards against ID changes
