### ISSUE TITLE
Crash with latest project E version 1.9.3h

### ISSUE THREAD

**Issue by escman1999** [Lilylicious/ThaumicEquivalence#8]
https://paste.ee/p/NHVev

**Comment by Lilylicious** [comment]
It's caused by another thaumcraft mod adding a Shaped Arcane Workbench recipe with the output (I think) not assigned to the output variable in the recipe. I don't know which one of your thaumcraft mod does it though. Working on a fix that'd fix it in general, not just for specific mods.

**Comment by Lilylicious** [comment]
Fixed as of 1.0.2
